name: issue_notifications
on: issue_comment

jobs:

  issue_comment_new:
    if: github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: 'New comment on issue #${{ github.event.issue.number }}: "${{ github.event.issue.title }}"'
          summary: 'New comment on issue #${{ github.event.issue.number }}: "${{ github.event.issue.title }}"'
          sections: '[{ "activityTitle": "[${{ github.event.comment.user.login }}](${{ github.event.comment.user.html_url }})", "activitySubtitle": "${{ github.event.comment.body }}", "activityImage": "${{ github.event.comment.user.avatar_url }}" }]'
          actions: '[{ "@type": "OpenUri", "name": "View comment", "targets": [{ "os": "default", "uri": "${{ github.event.comment.html_url }}" }] }]'
          theme_color: '58a6ff'