name: issue_notifications
on: issues

jobs:

  issue_new:
    if: ${{ github.event.action }} == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "New issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
          message: "${{ github.event.issue.body }}"
          color: "info"
          timezone: "Europe/Berlin"
