name: test-build-release
on:
  push:
    branches:
      - main

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "Neuer Commit"
          summary: "<Message Summary>"
          text: "<Message Text>"
          theme_color: "FF0000"
          sections: '[{ "activityTitle": "hello world", "activityImage": "https://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg", "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, s" }]'
          actions: '[{ "@type": "OpenUri", "name": "lorem ipsum", "targets": [{ "os": "default", "uri": "https://localhost" }] }]'