name: test-build-release
on:
  push:
    branches:
      - main

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: 'New commit: "${{ github.event.commit.message }}"'
          summary: 'New commit: "${{ github.event.commit.message }}"'
          theme_color: "7ee787"
          sections: '[{ "activityTitle": "[${{ github.event.commit.committer.name }}](${{ github.event.commit.author.html_url }})", "activitySubtitle": "+${{ github.event.commit.stats.addtions }} additions\n-${{ github.event.commit.stats.addtions }} deletions", "activityImage": "${{ github.event.commit.author.avatar_url }}"" }]'
          actions: '[{ "@type": "OpenUri", "name": "Show commit", "targets": [{ "os": "default", "uri": "${{ github.event.html_url }}" }] }]'